;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Equipment.Hand",DevComment="手持类道具")
+GameplayTagList=(Tag="Equipment.Hand.Axe",DevComment="消防斧")
+GameplayTagList=(Tag="Equipment.Grip.OneHand",DevComment="单手拿")
+GameplayTagList=(Tag="Equipment.Grip.TwoHand",DevComment="双手拿")
+GameplayTagList=(Tag="Equipment.Helmet",DevComment="头部装备")
+GameplayTagList=(Tag="Equipment.Suit",DevComment="身体装备")
+GameplayTagList=(Tag="Interaction.Door.Closed",DevComment="")
+GameplayTagList=(Tag="Interaction.Door.Open",DevComment="")
+GameplayTagList=(Tag="Interaction.Switcher.Off",DevComment="")
+GameplayTagList=(Tag="Interaction.Switcher.On",DevComment="")

